swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions:
    get:
      security:
        - Bearer : []
      tags:
      - User transaction
      summary: "Get all transactions"
      description: "Get all transactions of the transactions list"
      produces:
      - "application/json"
      parameters:
      - in: header
        type : string
        name: Authorization
        description: Attach Bearer JWT token
        required: true
      responses:
        '200':
          description: Transactions completed successfully
          schema:
            $ref: '#/definitions/Transactions'
        '401':
          description: Authorization error
        '404':
          description: Transactions does not exist
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - User transaction
      summary: User Transaction API
      description: API for fetching a user transaction
      parameters:
        - in: header
          type : string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '401':
          description: Authorization error
        '404':
          description: Transactions does not exist
        '500':
          description: Internal Server Error
  /user/transactions/{transactionID}:
    get:
      security:
        - Bearer : []
      tags:
      - Transaction View
      summary: "Get a single transaction"
      description: "Get a single transaction of the transactions list"
      produces:
      - "application/json"
      parameters: 
      - in: path
        name: transactionID
        description: Id of transaction
        required: true
        type: string
      responses:
        '200':
          description: "Transaction retrieved successfully"
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Authorization error
        '404':
          description: Transaction does not exist
        '500':
          description: Internal Server Error
  /user/transactions/{transactionID}/details:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction View
      summary: Transaction details
      description: Details of transaction choosen
      parameters:
        - in: header
          type : string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/BodyTransactionsDetails'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successully
          schema:
            $ref: '#/definitions/TransactionDetails'
        '401':
          description: Authorization error
        '404':
          description: Transaction details does not exist
        '500':
          description: Internal Server Error
  /user/transactions/{transactionID}/edit/category:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction View
      summary: Edit transaction category
      description: Update category of a transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update category
          required: true
          schema:
            $ref: '#/definitions/EditBody'
      produces:
        - application/json
      response:
        '200' :
           description: Update category successully.
           schema:
            $ref: '#/definitions/Edit'
        '401':
          description: Authorization error
        '404':
          description: Update error
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction View
      summary: Delete transaction category
      description: Delete category of a transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Delete choosen category
          required: true
          schema:
            $ref: '#/definitions/EditBody'
      produces:
        - application/json
      response:
        '200' :
           description: Delete category successully.
           schema:
            $ref: '#/definitions/Edit'
        '401':
          description: Authorization error
        '404':
          description: Delete is not possible
        '500':
          description: Internal Server Error
  /user/transactions/{transactionID}/edit/notes:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction View
      summary: Edit transaction notes
      description: Update notes of a transaction
      parameters:
      - in: header
        type : string
        name: Authorization
        description: Attach Bearer JWT token
        required: true
      - in: body
        name: body
        description: Update notes
        required: true
        schema:
          $ref: '#/definitions/EditBody'
        produces:
          - application/json
        responses:
          '200':
            description: Update notes successully
            schema:
              $ref: '#/definitions/Edit'
          '400':
            description: Update Invalid
          '500':
            description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction View
      summary: Delete transaction notes
      description: Delete notes of a transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Delete choosen notes
          required: true
          schema:
            $ref: '#/definitions/EditBody'
      produces:
        - application/json
      response:
        '200' :
           description: Delete notes successully.
           schema:
            $ref: '#/definitions/Edit'
        '401':
          description: Authorization error
        '404':
          description: Delete is not possible
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transaction:
    type: object
    properties:
      date:
        type: string
      description:
        type: string
      amount: 
        type: integer
        format: int64
      balance:
        type: integer
        format: int64
      transaction_type:
        type: string
        description: type of transaction 
      category:
        type: string
      note: 
        type: string
  Transactions:
    type: object
    description: Transaction lists for the month
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: ID of transaction
          date:
            type: string
            description: date of transaction making
          amount:
            type: number
            format: float
            description: amount of transaction in dollars
          balance:
            type: number
            format: float
            description: total amount in dollars
  BodyTransactionsDetails:
    type: object
    description: Details of transactions for the current month
    properties:
      id:
        type: integer
        description: ID of transaction
  TransactionDetails:
    type: object
    description: Details of the chosen transaction
    properties:
      status:
        type: integer
      message: 
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: ID of transaction in dollars
          date:
            type: string
            description: date of transaction
          description:
            type: string
            description: description of the transaction
          amount:
            type: number
            format: float
            description: amount of transaction in dollars
          balance:
            type: number
            format: float
            description: amount total in dollars
          transaction_type:
            type: string
            description: type of transaction
          category:
            type: string
            description: category of transaction
          notes:
            type: string
            description: notes of transaction
  EditBody : 
    type: object
    description: Your action is a success
    properties:
      id:
        type: integer
        description: id of transaction
      category:
        type: string
      note:
        type: string
  Edit :
    type: object
    description : Your action is a success
    properties:
      status:
        type: integer
      message:
        type: string 