swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  user/transaction:
     post:
      security:
        - Bearer: []
      tags:
        - User transaction
      summary: User Transaction API
      description: API for fetching a user transaction
      parameters:
        - in: header
          type : string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Datas
        '500':
          description: Internal Server Error
  user/transaction/details:
     post:
      security:
        - Bearer: []
      tags:
        - User transaction
      summary: User Transaction API
      description: API for fetching a user transactions
      parameters:
        - in: header
          type : string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/BodyTransactionsDetails'
      produces:
        - application/json
      responses:
        '200':
          description: User transaction details retrieved successully
          schema:
            $ref: '#/definitions/TransactionDetails'
        '400':
          description: Invalid Datas
        '500':
          description: Internal Server Error
  user/transaction/edit/category:
    put:
      security:
        - Bearer: []
      tags:
        - User transaction
      summary: User Transaction API
      description: API for fetching a user transactions
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update category
          required: true
          schema:
            $ref: '#/definitions/EditBodyTransactionCategory'
      produces:
        - application/json
      response:
        '200' :
           description: Update category successully.
           schema:
            $ref: '#/definitions/EditTransactionCategory'
        '400':
          description: Update Invalid
        '500':
          description: Internal Server Error
  user/transaction/edit/notes:
    put:
      security:
        - Bearer: []
      tags:
        - User transaction
      summary: User Transaction API
      description: API for fetching a user transactions
      parameters:
      - in: header
        type : string
        name: Authorization
        description: Attach Bearer JWT token
        required: true
      - in: body
        name: body
        description: Update notes
        required: true
        schema:
          $ref: '#/definitions/EditBodyTransactionNote'
        produces:
          - application/json
        responses:
          '200':
            description: Update notes successully
            schema:
              $ref: '#/definitions/EditTransactionNote'
          '400':
            description: Update Invalid
          '500':
            description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transactions:
    type: object
    description: Transaction lists for the month
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: ID of transaction
          date:
            type: string
            description: date of transaction making
          amount:
            type: number
            format: float
            description: amount of transaction in dollars
          balance:
            type: number
            format: float
            description: total amount in dollars
  BodyTransactionsDetails:
    type: object
    description: Details of transactions for the current month
    properties:
      id:
        type: integer
        description: ID of transaction
  TransactionDetails:
    type: object
    description: Details of the chosen transaction
    properties:
      status:
        type: integer
      message: 
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: ID of transaction in dollars
          date:
            type: string
            description: date of transaction
          description:
            type: string
            description: description of the transaction
          amount:
            type: number
            format: float
            description: amount of transaction in dollars
          balance:
            type: number
            format: float
            description: amount total in dollars
          transaction_type:
            type: string
            description: type of transaction
          category:
            type: string
            description: category of transaction
          notes:
            type: string
            description: notes of transaction
  EditBodyTransactionCategory : 
    type: object
    description: edit category of current transaction
    properties:
      id:
        type: integer
        description: id of current transaction
      category:
        type: string
        description: category name of current transaction
  EditTransactionCategory :
    type: object
    description : category of this transaction. Update.
    properties:
      status:
        type: integer
      message:
        type: string
  EditBodyTransactionNote : 
      type: object
      description : edit note of this transaction.
      properties :
        id :
          type : integer
          description : id of current transaction
        note :
          type : string
          description: notes of current transaction
  EditTransactionNote :
    type: object
    description : note of this transaction. Update.
    properties:
      status:
        type: integer
      message:
        type: string   