swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}:
    get:
      security:
        - Bearer : []
      tags:
      - User Transactions
      summary: Get all accounts of user's
      description: API for getting all accounts
      produces:
      - "application/json"
      parameters:
      - in: header
        type : string
        name: Authorization
        description: Attach Bearer JWT token
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: string
        required: true
      responses:
        '200':
          description: Account's of users received
        '401':
          description: Authorization error
        '404':
          description: Accounts list does not exist
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions:
    get:
      security:
        - Bearer : []
      tags:
      - User Transactions
      summary: Get all transactions of specific account ID
      description: API for getting all transactions of specific account ID
      produces:
      - "application/json"
      parameters:
      - in: header
        type : string
        name: Authorization
        description: Attach Bearer JWT token
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: string
        required: true
      responses:
        '200':
          description: All transactions of your account have been received
          schema:
            $ref: '#/definitions/Transactions'
        '401':
          description: Authorization error
        '404':
          description: Maybe this account does not exist or the ID is wrong
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Get a specific transaction in list transactions
      description: API for getting a specific transaction in a list transactions
      parameters:
        - in: header
          type : string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          description: User's account ID
          type: string
          required: true
        - in: path
          name: transactionId
          description: Transaction ID to get
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction sending successully
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Authorization error
        '404':
          description: Transactions does not correct
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Posting a new transaction to the list of transactions
      description: API for posting a new transaction in a transactions list
      parameters:
        - in: header
          type : string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          description: User's account ID
          type: string
          required: true
        - in: path
          name: transactionId
          description: Transaction ID to create
          type: string
          required: true
        - in: body
          name: body
          description: Transaction post
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction sending successully
          schema:
            $ref: '#/definitions/Transactions'
        '401':
          description: Authorization error
        '404':
          description: Transactions does not correct
        '500':
          description: Internal Server Error
    put:
      security:
      - Bearer: []
      tags:
      - User Transactions
      summary: Edit transaction
      description: Update current transaction
      parameters:
      - in: header
        type: string
        name: Authorization
        description: Attach Bearer JWT token
        required: true
      - in: path
        name: AccountId
        description: Id of account with the transaction to update
        required: true
        type: string
      - in: path
        name: transactionID
        description: Id of transaction to update
        required: true
        type: string
      - in: body
        name: body
        description: Update transaction
        required: true
        schema:
          $ref: '#/definitions/Transaction'
      produces:
      - application/json
      response:
      '200' :
          description: Update transaction successully.
      '401':
        description: Authorization error
      '404':
        description: Update error
      '500':
        description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Delete current transaction
      description: Delete transaction with this ID
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: string
          name: accountID
          description: Id of account who has the transaction to delete
          required: true
        - in: path
          type: string
          name: transactionId
          description: Id of transaction to delete
          required: true
      produces:
        - application/json
      response:
        '200' :
           description: Delete transaction successully.
        '401':
          description: Authorization error
        '404':
          description: Delete is not possible
        '500':
          description: Internal Server Error    
  /user/accounts/{accountId}/transactions/{transactionId}/category:
    put:
      security:
      - Bearer: []
      tags: 
      - Transaction View
      summary: Edit transaction category
      description: API to edit category of a specific transaction
      parameters:
      - in: header
        type: string
        name: Authorization
        description: Attach Bearer JWT token
        required: true
      - in: path
        name: accountID
        description: Id of account
        type: string
      - in: path
        name: transactionID
        description: Id of transaction
        required: true
        type: string
      - in: body
        name: body
        description: Update category of this transaction
        required: true
        schema:
          $ref: '#/definitions/TransactionsUpdateCategory'
      consumes:
      - application/json
      produces:
      - application/json
      response:
      '200' :
          description: Update category successully.
          schema:
            $ref: '#/definitions/Transactions'
      '401':
        description: Authorization error
      '404':
        description: Update category error, maybe ID of this account or ID of this transaction false
      '500':
        description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionId}/notes:
    put:
      security:
      - Bearer: []
      tags: 
      - Transaction View
      summary: Edit transaction notes
      description: API to edit notes of a specific transaction
      parameters:
      - in: header
        type: string
        name: Authorization
        description: Attach Bearer JWT token
        required: true
      - in: path
        name: accountID
        description: Id of account
        type: string
      - in: path
        name: transactionID
        description: Id of transaction
        required: true
        type: string
      - in: body
        name: body
        description: Update category of this transaction
        required: true
        schema:
          $ref: '#/definitions/TransactionsUpdateNotes'
      consumes:
      - application/json
      produces:
      - application/json
      response:
      '200' :
          description: Update notes successully.
          schema:
            $ref: '#/definitions/Transactions'
      '401':
        description: Authorization error
      '404':
        description: Update notes error, maybe ID of this account or ID of this transaction false
      '500':
        description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transaction:
    type: object
    properties:
      date:
        type: string
      description:
        type: string
      amount: 
        type: integer
        format: int64
      balance:
        type: integer
        format: int64
      transaction_type:
        type: string
        description: type of transaction 
      category:
        type: string
      note: 
        type: string
  Transactions:
    type: object
    description: Transaction lists for the month
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: ID of transaction
          date:
            type: string
            description: date of transaction making
          amount:
            type: number
            format: float
            description: amount of transaction in dollars
          balance:
            type: number
            format: float
            description: total amount in dollars
  TransactionsUpdateCategory:
    type: object
    properties:
      category:
        type: string
  TransactionsUpdateNotes:
    type: object
    properties:
      notes:
        type: string
  BodyTransactionsDetails:
    type: object
    description: Details of transactions for the current month
    properties:
      id:
        type: integer
        description: ID of transaction
  TransactionDetails:
    type: object
    description: Details of the chosen transaction
    properties:
      status:
        type: integer
      message: 
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: ID of transaction in dollars
          date:
            type: string
            description: date of transaction
          description:
            type: string
            description: description of the transaction
          amount:
            type: number
            format: float
            description: amount of transaction in dollars
          balance:
            type: number
            format: float
            description: amount total in dollars
          transaction_type:
            type: string
            description: type of transaction
          category:
            type: string
            description: category of transaction
          notes:
            type: string
            description: notes of transaction
    type: object
    description : Your action is a success
    properties:
      status:
        type: integer
      message:
        type: string 